stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - pwd
    - mvn package
    - service ab stop
    - cp target/active-bystander-1.0-SNAPSHOT.jar /var/ab-cd
    - service ab start
  only:
    - master
