stages:
  - build
  - test
  - deploy_staging
  - deploy_production

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

deploy_staging:
  stage: deploy
  script:
    - pwd
    - mvn package
    - service ab-staging stop
    - cp target/active-bystander-1.0-SNAPSHOT.jar /var/ab-cd-staging
    - service ab-staging start
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - pwd
    - mvn package
    - service ab-production stop
    - cp target/active-bystander-1.0-SNAPSHOT.jar /var/ab-cd-production
    - service ab-production start
  only:
    - master
